### PR TITLE
Add disable bounding Box

### PR DESCRIPTION
**Pull request by MiniMasterDRC**
this option can improve performance in many cases by allowing better image resolutions to be used

### CODE REVIEW

**Comment by Bankaimaster999** [comment]
MMJR doesn't really have bounding box functionality though or at least the implementation isn't the same as Dolphin Official/other versions.
However I can add in the option to toggle it off before the game starts (even if it probably won't do much)

**Comment by Bankaimaster999** [comment]
Also once again if this is your way of posting a request and not code changes you made;
Then please don't post requests via PR otherwise I'll get confused on what exactly is someone contributing towards the build.

**Comment by MiniMasterDRC** [comment]
sorry I don't know how I published it in experimetal it's a pull request, I didn't know that this compilation didn't have this function, it helps a lot I use it in 10763 modifying the ini since the current one has the fifo change that weihuoya made from 11453 and some games give crashing and joystick problems ex: SA2B, Goldeneye well then I close it if it doesn't work friend

**Comment by Bankaimaster999** [comment]
> sorry I don't know how I published it in experimetal it's a pull request, I didn't know that this compilation didn't have this function, it helps a lot I use it in 10763 modifying the ini since the current one has the fifo change that weihuoya made from 11453 and some games give crashing and joystick problems ex: SA2B, Goldeneye well then I close it if it doesn't work friend

Ok ... I will look into making BBox a togglable option in the newer builds going forward. No ETA because I'm working on experimental stuff but if its taking too long I'll probably pop a build with just that option.

**Pull request closed without merging**
