### PR TITLE
UI: Replace emulation toolbar with Dolphin Emulator bar

### PR DESCRIPTION
**Pull request by Gamer64ytb**
This change removes toolbar to implement Dolphin Emulator bar, here a screenshot of the bar:
Screenshot_2022-02-04-19-03-30-439_org mmjr gamerytb

### CODE REVIEW

**Comment by kleidis** [comment]
Why

**Comment by Bankaimaster999** [comment]
I see what you're trying to do but I don't think its a best for MMJR 1.0 as there are already quick settings menu easily accessible with a swipe or back press (same or less screen interactions as Dolphin official menu.)

It would probably be better having a "Exit Emulation" confirmation GUI where it asks you Yes or No (yes = exit to main menu / no = return to game screen) instead when pressing the back button once.

**Comment by kleidis** [comment]
> It would probably be better having a "Exit Emulation" confirmation GUI where it asks you Yes or No (yes = exit to main menu / no = return to game screen) instead when pressing the back button once.

He already did that on Dolphin 360

**Comment by Hisham735** [comment]
Can someone please add rvz format support to any mmj version.. Iso taking a lot of space and not any mmj based support rvz 😣

**Comment by kleidis** [comment]
> Can someone please add rvz format support to any mmj version.. Iso taking a lot of space and not any mmj based support rvz 😣

Both @Bankaimaster999 and @Gamer64ytb have tried that
It's too complex to add

**Comment by BNKMST999** [comment]
> Can someone please add rvz format support to any mmj version.. Iso taking a lot of space and not any mmj based support rvz 😣

Yeah that's not gonna happen ... stick with Official or MMJR2 ...

**Comment by BNKMST999** [comment]
> > It would probably be better having a "Exit Emulation" confirmation GUI where it asks you Yes or No (yes = exit to main menu / no = return to game screen) instead when pressing the back button once.
> 
> He already did that on Dolphin 360

... so then; why all this extra stuff; not that its a QOL improved feature compared to the previous menu?

**Pull request closed without merging**
